<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.MusicTagShelf</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.MusicTagShelf</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.9.0.0</Version>
    <FileVersion>1.9.0.0</FileVersion>
    <AssemblyVersion>1.9.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.11.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <None Remove="Resources\genres.json" />
    <EmbeddedResource Include="Resources\genres.json" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Jellyfin.Plugin.MusicTagShelf.Tests/**" />
    <None Remove="Jellyfin.Plugin.MusicTagShelf.Tests/**" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Jellyfin.Plugin.MusicTagShelf.Tests" />
  </ItemGroup>
</Project>
